In [6]:
#1 zad
import numpy as np
array = np.array([0,1,2,3,4,5,6,7,8,9])

dtype = array.dtype

ndim = array.ndim

shape = array.shape

typeO = type(array)


print(dtype)
print(ndim)
print(shape)
print(typeO)

print(array[2:-1]) #slicing

reshaped = np.reshape(array, [2,5]) #reshape
print(reshaped)

print(np.add(reshaped[0], reshaped[1])) #elementwise addition

int64
1
(10,)
<class 'numpy.ndarray'>
[2 3 4 5 6 7 8]
[[0 1 2 3 4]
 [5 6 7 8 9]]
[ 5  7  9 11 13]
